services:
  inventario-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped